# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MPPlayerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MPPlayerDemo
pod 'ZFPlayer'
pod 'KTVHTTPCache'
pod 'ZFPlayer/ControlView'

  target 'MPPlayerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MPPlayerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
